### ISSUE TITLE
Implement Breadcrumbs

### ISSUE THREAD

**Issue by poly2it** [wroyca/vscode-rounded#10]
From GNOME Files:
![Screenshot from 2023-05-14 21-26-20](https://github.com/wroyca/libadwaita-vscode-theme/assets/84731064/17843541-ecc6-4e0b-9f4b-c65b9d7ab04a)

Current libadwaita-vscode-theme:
![Screenshot from 2023-05-18 14-14-11](https://github.com/wroyca/libadwaita-vscode-theme/assets/84731064/27542b75-f5d5-46c9-852a-28f340a3a3d0)

Since the breadcrumbs from Files are quite heavily padded, it might be best to implement the breadcrumbs inline - ie. skip the background and only implement the custom text style/margins.

Also, should folders use `/` separators but code objects use the current `>` separators?

**Comment by wroyca** [comment]
> Also, should folders use `/` separators but code objects use the current `>` separators?

Ideally, yes, but it would necessitate making some adjustments using JS

**Comment by poly2it** [comment]
> > Also, should folders use `/` separators but code objects use the current `>` separators?
> 
> Ideally, yes, but it would necessitate making some adjustments using JS

This is what I have so far, without any JS.
![Screenshot from 2023-05-18 16-03-15](https://github.com/wroyca/libadwaita-vscode-theme/assets/84731064/4c7505d9-cac7-4d75-8787-fbf9b4e0abdf)

**Comment by poly2it** [comment]
@wroyca https://github.com/wroyca/libadwaita-vscode-theme/pull/11
