### ISSUE TITLE
The "Go to File" at the Top

### ISSUE THREAD

**Issue by putradnata** [wroyca/vscode-rounded#9]
I just updated the theme with:
`git pull`

Then reload it with `Reload Custom CSS and JS` it's working fine, until i press `Ctrl + P` and see if the pop-up not at center of the screen like before, it going back to the top :(

![image](https://github.com/wroyca/libadwaita-vscode-theme/assets/29300537/7b69f842-ebb8-460c-92ce-12432872b31c)

Any workaround for this? Thank you!

**Comment by wroyca** [comment]
Hello, it has been relocated to https://github.com/wroyca/libadwaita-vscode-theme/blob/main/src/miscellaneous.css to prevent interfering with other CSS files by incorporating experimental modifications.

Please make sure to modify your settings using the following:

```
"vscode_custom_css.imports": [
  "file:///home/username/libadwaita-vscode-theme/src/vs/workbench/browser/parts/editor/media/editorplaceholder.css",
  "file:///home/username/libadwaita-vscode-theme/src/vs/workbench/browser/parts/editor/media/tabstitlecontrol.css",
  "file:///home/username/libadwaita-vscode-theme/src/vs/workbench/contrib/interactiveEditor/browser/interactiveEditor.css",
  "file:///home/username/libadwaita-vscode-theme/src/miscellaneous.css"
]
```

I'm glad to know that someone is enjoying the centered widget ;)

**Comment by putradnata** [comment]
Wow, finally this comeback!
Thank you so much! :)

![image](https://github.com/wroyca/libadwaita-vscode-theme/assets/29300537/90a7ac55-6e2c-4215-be43-eef78906354f)


Yeah, i enjoy this and get used with the position after using it for a while, when it goes back to original (which is at the top) it make me confuse :(
